package com.web.demo.dto;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.web.multipart.MultipartFile;

import com.web.demo.entity.Games;

/**
 * SlideShow generated by hbm2java
 */


public class SlideShowDTO implements java.io.Serializable {

	private Integer idSlideShow;
	private Games games;
	private MultipartFile  image;

	public SlideShowDTO() {
	}

	public SlideShowDTO(Games games, MultipartFile  image) {
		this.games = games;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_slide_show", unique = true, nullable = false)
	public Integer getIdSlideShow() {
		return this.idSlideShow;
	}

	public void setIdSlideShow(Integer idSlideShow) {
		this.idSlideShow = idSlideShow;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game")
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	@Column(name = "image", length = 45)
	public MultipartFile  getImage() {
		return this.image;
	}

	public void setImage(MultipartFile  image) {
		this.image = image;
	}

}
