package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ViewBlog generated by hbm2java
 */
@Entity
@Table(name = "view_blog", catalog = "megalodondb")
public class ViewBlog implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_view_blog", unique = true, nullable = false)
	private Integer idViewBlog;
	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	private Date date;
	@Column(name = "count_view")
	private Integer countView;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "viewBlog")
	private Set<Blog> blogs = new HashSet<Blog>(0);

	public ViewBlog() {
	}

	public ViewBlog(Date date, Integer countView) {
		this.date = date;
		this.countView = countView;
//		this.blogs = blogs;
	}

	
	public Integer getIdViewBlog() {
		return this.idViewBlog;
	}

	public void setIdViewBlog(Integer idViewBlog) {
		this.idViewBlog = idViewBlog;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public Integer getCountView() {
		return this.countView;
	}

	public void setCountView(Integer countView) {
		this.countView = countView;
	}

	
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

}
